[package]
name = "crypto"
version = "0.1.0"
authors = ["geNAZt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.16.0"
libflate = "1.0.1"
lazy_static = "1.4.0"

[lib]
crate-type = ["cdylib"]