[package]
name = "crypto"
version = "0.1.0"
authors = ["geNAZt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.16.0"
libflate = "1.0.1"
cfb8 = "0.4.0"
aes = "0.4.0"
sha2 = "0.9.1"
byteorder = "1.3.4"

[lib]
crate-type = ["cdylib"]