/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_gomint_crypto_NativeProcessor */

#ifndef _Included_io_gomint_crypto_NativeProcessor
#define _Included_io_gomint_crypto_NativeProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_gomint_crypto_NativeProcessor
 * Method:    createNewContext
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_io_gomint_crypto_NativeProcessor_createNewContext
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     io_gomint_crypto_NativeProcessor
 * Method:    destroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_gomint_crypto_NativeProcessor_destroyContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_gomint_crypto_NativeProcessor
 * Method:    process
 * Signature: (JLio/gomint/crypto/SizedMemoryPointer;)Lio/gomint/crypto/SizedMemoryPointer;
 */
JNIEXPORT jobject JNICALL Java_io_gomint_crypto_NativeProcessor_process
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
