on: [push]

name: CI

jobs:
  maven:
    needs:
      - windows_x64
      - linux_x64
    name: Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: crypto.dll
          path: src/main/resources
      - uses: actions/download-artifact@master
        with:
          name: libcrypto.so
          path: src/main/resources
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
  windows_x64:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-msvc
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: install
          args: xargo
      - run: xargo build --target x86_64-pc-windows-msvc --release --manifest-path crypto/Cargo.toml
        env:
          RUSTFLAGS: "-C target-feature=+aes,+ssse3"
      - uses: actions/upload-artifact@master
        with:
          name: crypto.dll
          path: crypto/target/x86_64-pc-windows-msvc/release/crypto.dll
  linux_x64:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MingW
        run: sudo apt-get install -y tree binutils
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: install
          args: xargo
      - run: xargo build --target x86_64-unknown-linux-gnu --release --manifest-path crypto/Cargo.toml
        env:
          RUSTFLAGS: "-C target-feature=+aes,+ssse3"
      - run: strip -s -w -K Java_* crypto/target/x86_64-unknown-linux-gnu/release/libcrypto.so
      - uses: actions/upload-artifact@master
        with:
          name: libcrypto.so
          path: crypto/target/x86_64-unknown-linux-gnu/release/libcrypto.so