on: [push]

name: CI

jobs:
  windows_x64:
    name: Windows x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MingW
        run: sudo apt-get install -y gdb-mingw-w64 gcc-mingw-w64-x86-64 tree
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --release --manifest-path crypto/Cargo.toml
      - run: tree
  linux_x64:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MingW
        run: sudo apt-get install -y tree
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-linux-gnu --release --manifest-path crypto/Cargo.toml
      - run: tree