on: [push]

name: CI

jobs:
  windows_x64:
    name: Windows x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        working-directory: ./crypto
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release
  linux_x64:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        working-directory: ./crypto
        with:
          command: build
          args: --release